/*
AUTORES :Javier González Brito .
        :Javier ...
        :Izan ...
        :Arian...
        :Jose...
ULT FECHA: 17/04/2023
Clase Personaje
COMENTARIOS: Clase principal del personaje
*/

#include "grafo.h"
